export const KNOWN_SITUATIONS = [
  {
    slug: 'ukraine-war',
    name: 'Война в Украине',
    type: 'conflict',
    lat: 48.4, lng: 31.2,
    wikiSlug: 'Russian_invasion_of_Ukraine',
    searchTerms: 'Ukraine war Russia invasion front',
  },
  {
    slug: 'gaza-war',
    name: 'Война в Газе',
    type: 'conflict',
    lat: 31.5, lng: 34.4,
    wikiSlug: 'Gaza_war',
    searchTerms: 'Gaza Israel Hamas war ceasefire',
  },
  {
    slug: 'sudan-war',
    name: 'Война в Судане',
    type: 'conflict',
    lat: 15.5, lng: 32.5,
    wikiSlug: 'Sudanese_civil_war_(2023–present)',
    searchTerms: 'Sudan civil war RSF SAF Khartoum',
  },
  {
    slug: 'myanmar-conflict',
    name: 'Гражданская война в Мьянме',
    type: 'conflict',
    lat: 19.7, lng: 96.1,
    wikiSlug: 'Myanmar_civil_war_(2021–present)',
    searchTerms: 'Myanmar Burma civil war junta',
  },
  {
    slug: 'yemen-war',
    name: 'Война в Йемене',
    type: 'conflict',
    lat: 15.5, lng: 48.5,
    wikiSlug: 'Yemeni_civil_war_(2014–present)',
    searchTerms: 'Yemen Houthi war ceasefire Saudi',
  },
  {
    slug: 'syria-conflict',
    name: 'Война в Сирии',
    type: 'conflict',
    lat: 34.8, lng: 38.9,
    wikiSlug: 'Syrian_civil_war',
    searchTerms: 'Syria war Assad rebel offensive',
  },
  {
    slug: 'sahel-crisis',
    name: 'Нестабильность в Сахеле',
    type: 'conflict',
    lat: 15.0, lng: -2.0,
    wikiSlug: 'Sahel_conflict',
    searchTerms: 'Sahel Mali Burkina Faso Niger coup jihadist',
  },
  {
    slug: 'taiwan-strait',
    name: 'Тайваньский пролив',
    type: 'political',
    lat: 23.5, lng: 121.0,
    wikiSlug: 'Cross-strait_relations',
    searchTerms: 'Taiwan China strait tension military PLA',
  },
  {
    slug: 'north-korea',
    name: 'Северная Корея',
    type: 'political',
    lat: 40.0, lng: 127.0,
    wikiSlug: 'North_Korea',
    searchTerms: 'North Korea missile nuclear Kim Jong-un',
  },
  {
    slug: 'ethiopia-tigray',
    name: 'Конфликт в Эфиопии',
    type: 'conflict',
    lat: 14.0, lng: 38.5,
    wikiSlug: 'Tigray_War',
    searchTerms: 'Ethiopia Tigray war famine conflict Amhara',
  },
];

export const KNOWN_SLUGS = KNOWN_SITUATIONS.map(s => s.slug);
